# ???? ?? ????? SQLite
url=jdbc:sqlite:sample.db
driver=org.sqlite.JDBC

# changelog (????? ? resources)
changeLogFile=src/main/resources/db/changelog/changelog.xml

# ????? ??? history
username=sa
password=